first_day_of_water_year = 121

[components.dry_season_baseflow]
characteristics = [
    "timing",
    "magnitude",
    "duration",
]
parameters = [
    [
        245,
        366,
    ],
    [
        1,
        0.011,
        ">",
    ],
    [
        7,
        [
            1,
            0,
        ],
        ">",
    ],
]
scoring_pattern = [
    1,
    0,
    1,
]

[components.november_pulse_flow]
characteristics = [
    "timing",
    "magnitude",
    "rate_of_change",
]
parameters = [
    [
        185,
        215,
    ],
    [
        1,
        2.256,
        ">",
    ],
    [
        1,
        2.0,
        ">",
    ],
]
scoring_pattern = [
    1,
    1,
    1,
]
